### ISSUE TITLE
Settings schema does not contain a key named 'regex'

### ISSUE THREAD

**Issue by DagBjorndal** [SoongNoonien/mpdevil#10]
Thank you for your good work, which I have enjoyed daily for some time now.

I am excited to see that you have finished a new version. It seems to install fine with 

`sudo apt -y install ./mpdevil_0.9.1-1_all.deb`

on my Raspberry Pi 4B with Raspberry Pi O, but when attempting to run, I get

> (mpdevil:2093): GLib-GIO-ERROR **: 23:30:07.618: Settings schema 'org.mpdevil' does not contain a key named 'regex'
Sporings-/stoppunkts-felle

Please direct me what to do.

**Comment by SoongNoonien** [comment]
> Thank you for your good work, which I have enjoyed daily for some time now.

Nice to hear!

> (mpdevil:2093): GLib-GIO-ERROR **: 23:30:07.618: Settings schema 'org.mpdevil' does not contain a key named 'regex'
> Sporings-/stoppunkts-felle

The 'regex' key is new and was introduced in version `0.8.5`. So if you manually installed a version `<0.8.5` to a location like `/usr/local` (which is the default for a manual installation) this will have priority over the new installation of `0.9.1` by apt/dpkg. If you did not remove the old version or install a newer version since your last bug report #9 this is probably causing the issue.

There are three possible solutions:
- You still have the old build directory then you can simply enter it and run `sudo make uninstall`
- You removed the old build directory then you could install it (the old version <0.8.5) again by reproducing the exact steps from last time and run `sudo make uninstall` afterwards
- Remove the old version by hand which can be really easy if you did not install any other programs to `/usr/local`. The file causing the problem is `/usr/local/share/glib-2.0/schemas/org.mpdevil.gschema.xml`. If there is no other `.xml` file in that directory remove it entirely. If there are any other `.xml` files run `sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas` afterwards.

I hope this resolves your problem.

**Comment by DagBjorndal** [comment]
I had version 0.8.4. Couldn't find the build folder, so I went for solution 3, and deleted the .xml-file. 

This didn't immediately work. I then ran the glib-compile-schemas command, which removed the other file in the directory. Now it works. Thank you, Martin!

MPDevil is wicked :-)
