### ISSUE TITLE
main pane stops working after encountering certain files

### ISSUE THREAD

**Issue by apfelkuchen6** [SoongNoonien/mpdevil#11]
Hey,

On my machine mpdevil stops updating the main pane after encountering certain files.

### Steps to reproduce
1. Place [this file](https://stuff.hrnz.li/lol.flac) somewhere in your mpd music directory
2. Place it at the current position in the playing queue.
3. Start mpdevil.

### Observed behaviour
1. mpdevil outputs
```
Traceback (most recent call last):
  File "/usr/bin/mpdevil", line 359, in _on_song_changed
    self._update_metadata()
  File "/usr/bin/mpdevil", line 340, in _update_metadata
    self._metadata[key]=self.implemented_tags[key](value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
Traceback (most recent call last):
  File "/usr/bin/mpdevil", line 2102, in _refresh
    callback()
  File "/usr/bin/mpdevil", line 2076, in callback
    discs=int(album["songs"][-1].get("disc", 1))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```
2. The main pane stays empty, even after selecting other artists: ![](https://stuff.hrnz.li/mpdevil.png)

This happens both with the latest release and current HEAD.

### Expected behaviour
The main pane keeps working.

Thanks for all the work.

**Comment by SoongNoonien** [comment]
Hi!
I published a commit which fixes this issue. It was caused by the tags of your file. Some MPD commands return multiple values of the track and disc field of your file. This is a bit inconsistent since the raw metadata by using the `lsinfo` command get reported like this: 
![Bildschirmfoto_2020-10-17_09-35-20](https://user-images.githubusercontent.com/49582808/96334019-cf47c900-106d-11eb-9ce8-fd188fe75b27.png)
(right click on the title)

Please let me no if it works like expected for you.

Martin

**Comment by apfelkuchen6** [comment]
Yes, this works perfectly. Thanks for the quick fix!
