### ISSUE TITLE
Explicit use of bindtextdomain for gettext? (NixOS, non-FHS)

### ISSUE THREAD

**Issue by bloomvdomino** [SoongNoonien/mpdevil#17]
Hello!

I've packaged und submitted `mpdevil` for NixOS. In the initial submitted package only the original strings are available, even though the translations are created and installed.

The reason for this is the way how NixOS is working. Nix(OS) has an so-called `nix-store` where the output of every 'derivation' (means a package here) is placed. In the corresponding folder the files are placed most of time FHS-conform, but prefixed with the nix-store folder (e.g. `/nix/store/qaqz01z1yf3ah2n68b258fdbchjyakn2-mpdevil-1.1.1/bin/mpdevil`)

**Now the point is:**

`mpdevil` only uses `textdomain("mpdevil")` without explicit usage of `bindtextdomain`. That results is the circumstance that `mpdevil` looks for the locale in the default system-wide locale folder (`/usr/share/locale` on most systems I believe). But on NixOS the locale is placed under `/nix/store/qaqz01z1yf3ah2n68b258fdbchjyakn2-mpdevil-1.1.1/share/locale`.

I got the locale working with patching `bin/mpdevil` to contain the `bindtextdomain` entry and then substite the path in a later build phase with the correct path. That's working, but it's not very elegant.

A bit more elegant would be to have the `bindtextdomain` line already in the source code and subsitute it with a static path (the previous mentioned hacky solution, but without patching -> atleast that's more the 'way of nix'). The best solution would be to implement something more dynamically, which gets the locale path more OS-independent, so it works on FHS _and_ non-FHS systems.

----

What do you think?

If you have are any questions about NixOS don't hesitate to ask me, maybe I can answer your question. :+1:

**Comment by SoongNoonien** [comment]
Hello!

> I've packaged und submitted mpdevil for NixOS.

 That's nice to hear!

I got a similar problem with the flatpak. To work around that I added a simple if statement to determine if mpdevil is running in a flatpak environment (see lines 34 and 35 in the code). For all the other systems I thought it would be the best to omit `bindtextdomain` since the OS knows best where to find the locals.  But I didn't think of NixOS. 

> A bit more elegant would be to have the bindtextdomain line already in the source code and subsitute it with a static path...

As the documentation of gettext (https://docs.python.org/3/library/gettext.html) states it would not change anything if I added a line like `bindtextdomain("mpdevil", None)` or `bindtextdomain("mpdevil", localedir=None)`. So you could replace `None` with the correct path. (I think with the extra `localedir` the matching/replacing would be a bit easier.) Is this what you meant? At least on my Gentoo installation this extra line behaves as expected.

> The best solution would be to implement something more dynamically, ...

Is there a way on NixOS to determine the right location (since `/nix/store/qaqz01z1yf3ah2n68b258fdbchjyakn2-mpdevil-1.1.1/share/locale` doesn't look so intuitive)? Another more general approach would be to determine the current location of the running mpdevil script (e.g. /nix/store/qaqz01z1yf3ah2n68b258fdbchjyakn2-mpdevil-1.1.1/bin/mpdevil) and reconstruct the locale path from there. But I haven't tried that yet.

**Comment by bloomvdomino** [comment]
> So you could replace None with the correct path. (I think with the extra localedir the matching/replacing would be a bit easier.) Is this what you meant?

That was exactly what I meant and what I've done in my patchfile; But I did this only to substitute it in the next step.

That would be the mpdevil part:

```
--- a/bin/mpdevil
+++ b/bin/mpdevil
@@ -31,6 +31,7 @@ import sys
 import re
 from gettext import gettext as _, ngettext, textdomain, bindtextdomain
 textdomain("mpdevil")
+bindtextdomain("mpdevil", localedir=None)
 if os.path.isfile("/.flatpak-info"):  # test for flatpak environment
 	bindtextdomain("mpdevil", "/app/share/locale")
 
```

So we can do the following in the nix derivation:

```
  preFixup = ''
    makeWrapperArgs+=("''${gappsWrapperArgs[@]}")
    substituteInPlace $out/bin/mpdevil \
      --replace "localedir=None" \
                "\"$out/share/locale\""
  '';
```

> Is there a way on NixOS to determine the right location of the locales (since /nix/store/qaqz01z1yf3ah2n68b258fdbchjyakn2-mpdevil-1.1.1/share/locale doesn't look so intuitive)?

> reconstruct the locale path from there

There are possibilities indeed. But I think none of them is OS-agnostic enough that it's a good idea to implement it.

---

I think the way to go should be the `localedir=None` variant. The statical link isn't a problem as NixOS always ensures that the path exists on the target.

**Comment by SoongNoonien** [comment]
> I think the way to go should be the `localedir=None` variant.

The newest commit implements this. I added `bindtextdomain("mpdevil", localedir=None)` to the else branch of the flatpak workaround to leave those two fixes completely separated. Please let me know if this is working with your NixOS build.

**Comment by bloomvdomino** [comment]
It works perfectly. :+1: 

I'll change it with the next version update :)
