### ISSUE TITLE
Add an entire artist to playlist

### ISSUE THREAD

**Issue by bloomvdomino** [SoongNoonien/mpdevil#18]
Currently it is only possible to add an album or track to the queue. If you wanna listen an entire artist, you are forced to click on every album with a middle mouse click. That's not a problem if you have just a few albums, but a bit annoying with more albums.

Maybe there is a convenient to add such an shortcut, interaction, click action, whatever … to add a whole artist?

**Comment by SoongNoonien** [comment]
I'm not really using that but I thought of it once. Currently it is only possible to directly add a whole artist via the search. The easiest solution would be to add an whole artist to the playlist via a middle click in the artist column on the left. But the shortcut 'a' which is used by the right click album preview, the search and the album overview wouldn't be possible since in the artist column the interactive search is enabled which starts on typing. But I wanted to get rid of these single letter shortcuts anyway to enable the interactive search in the album preview too. (I just don't have a better alternative.) Another solution would be to add a "fake" album to the album overview which contains all songs of the given artist. This would waste many space for a function which is not needed very often. Same applies to my third idea to add the action bar at the bottom from the search also to the album overview. I think this would also be very ugly. But the three buttons could be added to the album overview just like the lyrics button in the main cover. This would have to be configurable and I could add global key bindings just like for the lyrics button.

What do you think? My favorite solution is the first one but I have no good keybinding in mind for that yet.

**Comment by bloomvdomino** [comment]
I think the most intuitive solution would be indeed the first solution. Adding an artist via middle click seems to be the logical consequence of the album middle click. I don't know a good shortcut too, but I think finding a good one isn't impossible.

The fake album solution wouldn't be a good solution I think. If an artist e.g. only have one album the fake album button would be totally waste of space and irritating to the user.

The third solution sounds like an considerable alternative.

**Comment by SoongNoonien** [comment]
It is now possible to add whole artists via middle click. I also allowed to add all artists at once via a middle click on the "all artists" entry. This could be used to add for example all rock albums to the playlist.

> The third solution sounds like an considerable alternative.

Maybe I'll add this as an alternative to the middle click.

**Comment by SoongNoonien** [comment]
I have added shortcuts and a right click popover with the three buttons "append", "play" and "enqueue".

**Comment by bloomvdomino** [comment]
I have tested it a few days in the daily workflow. Works perfect!
