### ISSUE TITLE
Albums erroneously split by year

### ISSUE THREAD

**Issue by build2stone** [SoongNoonien/mpdevil#21]
I have an album which contains tracks of different years.
In the interface, this is displayed as multiple albums, when it's really one album.
Is there some way to fix this, or is it just a design decision?
(I'd like to avoid editing the metadata if possible)

**Comment by SoongNoonien** [comment]
Yes, this is a design decision to support remakes of albums (e.g. remaster) which usually have the same name as the original one but a different release date. But I'm not sure if anyone uses this very much, since such albums could be easily suffixed by "Remastered" or something like that. Allowing multiple years on one album would also raise some problems with the sorting by year and the displaying of the year. What would you expect to happen in such situations? I tested cantata with two albums which have the same name but different release dates (or one could say one album with two release dates) they get displayed as one album and cantata (randomly?) picks one year to display. Do you know a client which handles this different/better, so I can get some idea on how this is normally done?

**Comment by build2stone** [comment]
After poking around a bit, it seems that the solution is to use the "Original Date" tag, which denotes date of recording.
"Date" then means "date of album release", which allows it to be used to differentiate albums again.
Cantata displays the "Original Date" next to tracks if it differs from the album date ("Date" tag), but I don't think this is necessary.

Apparently mpd also supports "musicbrainz_id", which is used to tell albums apart (I didn't test this).

I'll close this for now, since my problem has been solved.

**Comment by SoongNoonien** [comment]
Oh, I see. That sounds reasonable.
