### ISSUE TITLE
Custom playlist creation support

### ISSUE THREAD

**Issue by dgcampea** [SoongNoonien/mpdevil#28]
Feature request: support for creating custom playlists

**Comment by dgcampea** [comment]
Adding tracks to a playlist that can be edited+saved and selected for playback later.

**Comment by SoongNoonien** [comment]
One of the main goals of mpdevil is to play music without playlist management. I never used such functionalities in other players so I think I'm very unqualified to implement this in a way such that it is appealing and intuitive for users who would use this. Furthermore I don't like to implement complex features I wouldn't use myself.

**Comment by Popkornium18** [comment]
@SoongNoonien Would you accept a PR implementing this feature?

**Comment by SoongNoonien** [comment]
Sorry, but most likely not. I think there are certainly enough MPD clients focusing on playlist management.

**Comment by Popkornium18** [comment]
I see. Yes, there are other clients with this functionality but most other mpd clients are either unmaintained, ugly or unintuitive to use. But I understand that you don't want to add features that you wouldn't use yourself.

**Comment by SoongNoonien** [comment]
I eventually started working on this. Please take a look at the "playlists" branch. I'd be happy to hear about your opinions.

**Comment by Popkornium18** [comment]
First off, thanks for implementing this. I think it is already perfectly usable and I really like it. There are a some minor things that could be tweaked IMO.

- When saving an existing playlist I think it would be great to have a confirmation dialog. I could see myself accidentally pressing the wrong save button.
- Basically the same would be nice to have for the delete button.
- It would be cool to see the number of songs and total duration next to the playlist name instead of at the bottom.

These suggestions would maybe involve a couple more changes and I could live without them, but I think it would be nice:
- At first I expected the playlist to be replaced and not appended when your clicking on it. You can still replace it with the delete button and then selecting a playlist, but maybe it would be possible to make replacing the default and put appending into a context menu. That would match the behavior when clicking on an album. If you would do it that way you could put other operations like save and delete in the context menu. Maybe it would be cool to rename playlists, that could also be part of that context menu.
- It would be nice to add a single song or a whole album to a saved playlist without opening it first, appending the song/album and then saving the playlist. That would mean that you could listen to an album and add a single song to a saved playlist without interrupting the currently playing album.

**Comment by SoongNoonien** [comment]
The playlists branch is now merged to master.

> When saving an existing playlist I think it would be great to have a confirmation dialog. I could see myself accidentally pressing the wrong save button.

I'm not sure about confirmation dialogs. Wouldn't it be very annoying to confirm every deletion or saving?

> It would be cool to see the number of songs and total duration next to the playlist name instead of at the bottom. 

I do not fully understand what you mean by that. The duration at the bottom doesn't belong to any stored playlist, it belongs to the current playlist/queue.

> At first I expected the playlist to be replaced and not appended when your clicking on it. You can still replace it with the delete button and then selecting a playlist, but maybe it would be possible to make replacing the default and put appending into a context menu. That would match the behavior when clicking on an album. If you would do it that way you could put other operations like save and delete in the context menu. Maybe it would be cool to rename playlists, that could also be part of that context menu.

I thought appending is the default since this it what mpd's "load" command does. But appending wouldn't exactly match the behaviour of clicking on an album. Clicking on an album keeps the currently playing song (if any) in the playlist. Do you think the confirmation dialogs are still needed when the save and delete buttons are in a context menu? Renaming should be relatively easy to implement.

> It would be nice to add a single song or a whole album to a saved playlist without opening it first, appending the song/album and then saving the playlist. That would mean that you could listen to an album and add a single song to a saved playlist without interrupting the currently playing album.

This is possibly not very hard to implement but it is not easy to come up with a concept of how this should look and behave. The album and song context menus already have at least three buttons adding another one would make this even more "confusing". Maybe the third button is unneeded and can be dropped since this is the default action (but only when using the default settings) executed when clicking on a song/album. What about adding whole artists to a stored playlist, is this needed as well?

**Comment by Popkornium18** [comment]
> I'm not sure about confirmation dialogs. Wouldn't it be very annoying to confirm every deletion or saving?

Could be annoying, could be useful. I think if these options are put in a context menu a confirmation dialog will not be needed. If you do not want to do that I think it would be valuable for deleting since it's more destructive if done unintentionally and you do it so rarely.

> I do not fully understand what you mean by that. The duration at the bottom doesn't belong to any stored playlist, it belongs to the current playlist/queue.

I know but i think it would be nice to display the duration and number of songs of each playlist next to it's name, either in addition to the duration at the bottom or as a replacement. Personally I would be much more interested in the length of my saved playlists than the currently playing one. IIRC that information is available elsewhere anyway isn't it?

> I thought appending is the default since this it what mpd's "load" command does. But appending wouldn't exactly match the behaviour of clicking on an album. Clicking on an album keeps the currently playing song (if any) in the playlist.

I think this should be the default behavior for playlists as well. It just makes sense (to me at least) when everything works the same.

> This is possibly not very hard to implement but it is not easy to come up with a concept of how this should look and behave. The album and song context menus already have at least three buttons adding another one would make this even more "confusing". Maybe the third button is unneeded and can be dropped since this is the default action (but only when using the default settings) executed when clicking on a song/album. What about adding whole artists to a stored playlist, is this needed as well?

I understand that this would add a little clutter to the UI. I personally wouldn't want to add artists to playlists. Some music player allow that, and if you implement it for songs it kind of makes sense to also support it for albums and artists, but for me, adding single songs would be enough.

**Comment by SoongNoonien** [comment]
> IIRC that information is available elsewhere anyway isn't it?

No, not anymore.

I've added the duration hints and a context menu. All clicks and key presses should now do exactly the same as for an album. Renaming playlists and adding arbitrary songs (or even albums/artists) are to complex for now I will keep these features in mind and maybe add them in the future. I'd really like to port mpdevil to gtk4 before that to avoid implementing features twice, since gtk4 provides different widgets/features which may lead to a totally different solution.

**Comment by Popkornium18** [comment]
Do you intend to add the "Add song to Playlist" feature? I've been using the new playlists feature a lot and I love it. However I had the situation a couple of times where I was listening to a new album and thought "this song has to be in playlist X" but I also did not want to interrupt the album for that so I end up making notes for which songs need to go into which playlists and add them afterwards. It works but it's just a really clunky way of doing that.

**Comment by SoongNoonien** [comment]
> Do you intend to add the "Add song to Playlist" feature?

I'm still not sure about it. It adds complexity and some inconsistency, as we already discussed. Also, by implementing this I'd invite people to ask for even more playlist related features. 
Since the gtk4 port is not achievable yet, due to some bugs in gtk4, I thought about this issue recently. So I made some tests with the partitions feature of mpd because I think this could solve the problem without that much complexity. In fact this would also add the ability to modify playlists completely independent from the current playback. 
Do you think the partitions feature could fix this issue?

**Comment by SoongNoonien** [comment]
The test implementation can be found in the `partitions` branch. It currently supports switching between the "default" branch and another branch called "mpdevil". For an actual implementation we would possibly need some hint to show what partition is currently used. I'm not sure if a complete partitions support is even needed, perhaps it is enough to be able to switch to one other partition (which gets create if not already there).

**Comment by linnabraham** [comment]
> Do you intend to add the "Add song to Playlist" feature? I've been using the new playlists feature a lot and I love it. However I had the situation a couple of times where I was listening to a new album and thought "this song has to be in playlist X" but I also did not want to interrupt the album for that so I end up making notes for which songs need to go into which playlists and add them afterwards. It works but it's just a really clunky way of doing that.

I would like to second this opinion. Also when you want to create a custom playlist you might want to start off by listening to a small subset of songs (an existing playlist) rather than your entire music library. 

So implementing the "Add song to playlist" feature also helps in creating a new playlist from an existing playlist. I don't know of any other way to do this right now other than manually noting down the songs and doing it later like you have said.

**Comment by SoongNoonien** [comment]
@linnabraham And how is your opinion about the `partitions` branch?

**Comment by linnabraham** [comment]
> @linnabraham And how is your opinion about the `partitions` branch?

I haven't done much source building on Arch, so I wasn't sure how to go about with that. But it was surprisingly easy to do using the instructions in the readme. 

Initially I didn't understand how this would be useful. But now I think this is how I can achieve what I want. 

When hearing a song, switch to a different partition, search for the song and add it to queue. Click on the playlist menu and right click the name of the playlist and append and save. It's a lot of steps currently but at least I can get it done.

Really appreciate the work you are doing here. I am yet to find any other mpd client that is even half as good as this.

**Comment by SoongNoonien** [comment]
Ok, thanks for your thoughts on this. From your explanations I get the impression you're mostly adding (or would like to add) songs that are currently in the queue to stored playlists. Is that right? Would it be sufficient to be able to save songs from the current queue and not arbitrary ones from the library?

**Comment by Popkornium18** [comment]
> Do you think the partitions feature could fix this issue?

Yes, I think that would do the job. I think a full implementation of the partitions feature would be cool, but it's also significantly more work.

I think all in all I would still prefer an implementation in some context menu like for example Spotify does it, because it is more clear in what it does. I had to look up what this feature does, and how it could solve this problem, which is fine for me. It does the job, but it is a little harder to grasp.

I like that it possibly enables a lot of other use cases.
Maybe in a real implementation it shouldn't be placed so prominently in the UI, because I think most people wouldn't use the feature and could be annoyed by the "clutter".

**Comment by SoongNoonien** [comment]
Ok, and what do you think about my last comment? Especially about:
 > Would it be sufficient to be able to save songs from the current queue and not arbitrary ones from the library?

**Comment by linnabraham** [comment]
@SoongNoonien  For me, yes. That is exactly what I am trying to achieve. 

On a side-note, the real reason I am creating playlists in the first place is as part of a workaround to mpdevil or any of the other players not supporting filtering by tags like ```mood``` and others that I could use an ad-hoc playlist. The workaround is to use python and exiftool to create a playlist based on the ```mood``` column. The "Add to playlist" is just for a temporary list creation that I can later use for bulk editing the metadata tags. 

I am assuming that the reason all tags, that are supported by mpd, are not implemented in mpdevil is because it would increase the code base or clutter the UI. Is that right?

**Comment by Popkornium18** [comment]
> Would it be sufficient to be able to save songs from the current queue and not arbitrary ones from the library?

I would add songs from the queue more often, so it is definitely more important but I could see myself adding songs from the library as well.

**Comment by SoongNoonien** [comment]
I made an implementation of the "Add to playlist" feature in the `playlists` branch. I'm not sure if I like it, three popovers in a row look very weird. But I think using a dialog would be even worse. What do you think?

**Comment by SoongNoonien** [comment]
> I am assuming that the reason all tags, that are supported by mpd, are not implemented in mpdevil is because it would increase the code base or clutter the UI. Is that right?

The `mood` tag isn't even supported by any mpd release yet. As far as I know it will be available in 0.24. But all tags that are supported by mpd except the special musicbrainz tags are available in the search of mpdevil. The browser of mpdevil is optimized for "pop" music and should remain as simple as possible to be maintainable and easy to use. Some discussions about tags for classical music can be found here: https://github.com/SoongNoonien/mpdevil/pull/36

**Comment by linnabraham** [comment]
@SoongNoonien  If it was possible to integrate the add button into the already existing playlists button in the bottom row, it would have been better IMO.

Ya you are right about mpdevil supporting almost all of the mpd tags. It was just that there are lot more ID3 tags existing that mpd doesn't support. I probably confused the two. 

@Popkornium18  Ya. I was trying to do exactly that (happy, sad, calm, energetic and four more).

**Comment by SoongNoonien** [comment]
Ok, I've merged the `playlists` branch. Maybe the layout will change in the future when I get a better idea, suggestions are welcome.
