### ISSUE TITLE
Ignore letter case for (album) artists

### ISSUE THREAD

**Issue by dgcampea** [SoongNoonien/mpdevil#32]
Artists _Foo_ and _far_ are grouped separately in the left bar. The letter casing shouldn't matter here.

Note: Ignoring diacritics might not be a good idea since depending on the language it might represent different letters.
Further investigation leads to https://en.wikipedia.org/wiki/Collation which suggests that it might not be trivial to implement this. Perhaps there's a library that can be used here instead?

**Comment by SoongNoonien** [comment]
Ok, this was a though one. I hope it is now working correctly. Mpdevil now uses the LC_COLLATE environment variable to sort the artists. The first characters/letters are now shown in upper case and just once. Perhaps I'll change the sorting in the future since I'm currently forced to sort a second time just by the first character of the artists to ensure nothing like "-> test" is in between the artists starting with "t" (The German sorting curiously ignores things like "->".). Maybe I'll find another option to help finding artists which doesn't rely on the first letters.

Please let me know if it's working as expected.

**Comment by dgcampea** [comment]
Seems to be working with 975e0470ae3d30b813e1b1161aa59a9cf1227628. (for information, LC_COLLATE is unset)

**Comment by SoongNoonien** [comment]
> Seems to be working with 975e047.

Ok, good.

> (for information, LC_COLLATE is unset)

If LC_COLLATE is not explicitly set then in falls back to the systems default language, exactly like all the other LC_* vars. So it is sufficient to set LANG. The current state of all these vars can be queried by the `locale` shell command.
