### ISSUE TITLE
Multiple values for Album Artist cause duplicate artist entries

### ISSUE THREAD

**Issue by Popkornium18** [SoongNoonien/mpdevil#47]
This release has two different values set as the AlbumArtist tag. Mpdevil displays this correctly as a release for both artists, but generates a duplicate of the other artist, which contains only this release.

### Tags
![image](https://user-images.githubusercontent.com/46488511/153679764-ecaf64e4-2983-4f55-bbb3-23ff17aa4043.png)

### Correct first artist
![image](https://user-images.githubusercontent.com/46488511/153679351-b7e5a1fa-9477-4604-bc86-57cc281d3d3f.png)

### Duplicate second artist
![image](https://user-images.githubusercontent.com/46488511/153679403-1d256edb-8b2b-4863-9f81-0656f6576054.png)

### Duplicate first artist
![image](https://user-images.githubusercontent.com/46488511/153679477-d5aa806b-561e-4650-a367-1b1c0736e99b.png)

### Correct second artist
![image](https://user-images.githubusercontent.com/46488511/153679530-d00269d6-e7f3-4c05-b4de-d518cf379f2f.png)

**Comment by SoongNoonien** [comment]
Mpdevil uses the albumartistsort tag to populate the artist list. If there is no albumartistsort tag mpd falls back to albumartist, while this is the expected behaviour in most cases it has this unwanted side effect for albums with two albumartists. In such cases mpd returns all possible pairings of the albumartists when I request all albumartist/albumartistsort pairs. In your specific case this is (Burial, Burial), (Burial, Four Tet), (Four Tet, Burial) and (Four Tet, Four Tet), this also explains why two entries are listed under B and the other two under F. Currently the only option to fix this is to set one albumartistsort tag but this will make both entries appear at the same place in the list. But to be honest I'd consider multiple albumartists a tag issue, their shouldn't be any album with two albumartists.

**Comment by Popkornium18** [comment]
I'd say multiple AlbumArtists is correct in this case as it is more like a one-off collaboration between two already established artists. Ncmpcpp picks this up correctly.

**Comment by SoongNoonien** [comment]
Does ncmpcpp use the albumartistsort tags?

**Comment by Popkornium18** [comment]
> Does ncmpcpp use the albumartistsort tags?

I don't know. Judging from how it is handling compilations in my collection it might use the Artist tag.

**Comment by SoongNoonien** [comment]
Commit d80604b250a4775183ae663994b1b4e1c9e6b787 should fix this by proceeding as described above. Can you verify that?

**Comment by Popkornium18** [comment]
It works, thanks
