### ISSUE TITLE
Feature Request: Fast way to open an Album/Song in the default file browser

### ISSUE THREAD

**Issue by Popkornium18** [SoongNoonien/mpdevil#48]
I'm often in the situation that I find an issue in my tags like duplicate artists because of mismatched capitalization in the artist name.
Finding the album can be a bit annoying because of the way I sort my music (basically by 'source' e.g Web-DL, CD rip, Vinyl Rip and so on, which means the same artist can be in multiple locations). 

It would be nice if there was an option to open an album or a song in the default filebrowser. Alternatively making it possible to copy the file name from the context menu of a song would be helpful as well.

**Comment by SoongNoonien** [comment]
I had a similar problem some time ago. Therefore I implemented the "Open with…" button in the song context menu. Unfortunately when one selects a file browser in this open dialog this will not open the directory in which the song is contained instead it will use the default application for the mime type of the song file to open/play it. This wasn't a big problem for me since my tag problems can almost always be solved by simply opening the song with a tag editor chosen from this open dialog. But opening the songs location can often be more useful. I'll try to find a solution for this problem.

**Comment by Popkornium18** [comment]
I can't find the "Open with..." button. It should be in this menu, right?
![image](https://user-images.githubusercontent.com/46488511/156886708-3ca076d2-65cd-4b36-8a65-5d16a361f914.png)

**Comment by SoongNoonien** [comment]
Yes, but it is hidden when mpdevil can locate your files. Did you configure the right music library path in the profile settings?

**Comment by Popkornium18** [comment]
No I didn't. Now I see it.

**Comment by Popkornium18** [comment]
Maybe you could add the open folder function to the album while keeping open file to the songs.

**Comment by SoongNoonien** [comment]
> Unfortunately when one selects a file browser in this open dialog this will not open the directory in which the song is contained instead it will use the default application for the mime type of the song file to open/play it.

This seems to be not the case anymore. I tested it again and now it just opens the parent directory of the selected song when a file manager is chosen. I tested this with Thunar and Nautilus. Is this true on your machine as well?

> Maybe you could add the open folder function to the album while keeping open file to the songs.

I don't think this is a good solution since the album itself could be split about multiple directories. But I could modify the app chooser dialog to show an extra button just for launching the default file browser in the parent directory of the selected song.

**Comment by Popkornium18** [comment]
> This seems to be not the case anymore. I tested it again and now it just opens the parent directory of the selected song when a file manager is chosen. I tested this with Thunar and Nautilus. Is this true on your machine as well?

I tried it with Dolphin and it opened the file in the default handler for audio files and opened a nonexistent folder that has the same name as the audio file.

> I don't think this is a good solution since the album itself could be split about multiple directories. But I could modify the app chooser dialog to show an extra button just for launching the default file browser in the parent directory of the selected song.

Maybe it would be an option to always open the parent directory of the file and not the file itself? If you want to open just this file it is one extra click in the file browser. But it enables opening the directory easily without an additional button or some special logic.

**Comment by SoongNoonien** [comment]
> I tried it with Dolphin and it opened the file in the default handler for audio files and opened a nonexistent folder that has the same name as the audio file.

Perhaps this is configurable, I mean it's a kde program ;-) 

> Maybe it would be an option to always open the parent directory of the file and not the file itself? If you want to open just this file it is one extra click in the file browser. But it enables opening the directory easily without an additional button or some special logic.

You mean replacing the "Open with…" button?

**Comment by Popkornium18** [comment]
> Perhaps this is configurable, I mean it's a kde program ;-)
Can't find an option unfortunately.

> You mean replacing the "Open with…" button?
Yes. Imo if you only wanted to have one button, opening the folder would enable some usecases while being only slightly worse for others than opening the files directly. (An additional click and an additional window)

**Comment by SoongNoonien** [comment]
I found this: https://www.freedesktop.org/wiki/Specifications/file-manager-interface/
So I replaced the "Open with…" button with a "Show in file manager" button. This will launch the default file manager in the parent directory of the selected song while highlighting it. Please let me know if this fixes your problem.

**Comment by Popkornium18** [comment]
Works great, thanks
