### ISSUE TITLE
Sort by originaldate

### ISSUE THREAD

**Issue by brolyxxx** [SoongNoonien/mpdevil#51]
- OS: Arch Linux
- MPD version: 0.23.6
- mpdevil version: 1.7.0.r12.g22f452c-1 from [AUR](https://aur.archlinux.org/packages/mpdevil-git)

Hi, I started using your client and I really like it, however I'd like to be able to see my albums sorted by original release date (MPD tag `originaldate`) rather than recording date (the default MPD `date`). The reason is that when I look at the albums from a given artist, at first glance I wanna see when they were first released, not the date of the specific release I own.
Do you think it's something that can be implemented either as additional option in the settings or as a cli/config argument?

Thanks for the good work

**Comment by SoongNoonien** [comment]
Sorry, I won't implement that. It would introduce new inconsistencies with compilations where all songs have different `originaldate` tags while having one common `date` tag. I consider the `date` tag to be the release date of the specific version of the album because it is the only date related property which is always consistent across an entire album which makes it the natural choice to use for grouping/sorting of albums. But you could use the `albumsort` tag to achieve arbitrary sortings when "Sort albums by year" is disabled in the settings.
