### ISSUE TITLE
fix/update for Gentoo ebuild

### ISSUE THREAD

**Issue by xfzv** [SoongNoonien/mpdevil#82]
I would have made a PR for this but unfortunately the `.ebuild` isn't part of the repo. 

- [Python 3.11 is the default Python target on Gentoo since 2023-05-01](https://gitweb.gentoo.org/data/gentoo-news.git/commit/?id=bf718a7c9761e42e51c9deaa6a1fe7241be4c04a)
- `dev-python/python-mpd` was renamed to `dev-python/python-mpd2` on [2023-04-29](https://github.com/gentoo/gentoo/commit/1a320598fc3348032fcdf8add2693e84e8482b1c)

```diff
- PYTHON_COMPAT=( python3_{9,10} )
+ PYTHON_COMPAT=( python3_{11,12} )

- dev-python/python-mpd[${PYTHON_USEDEP}]
+ dev-python/python-mpd2[${PYTHON_USEDEP}]
```

Tested on my system, compiles fine.

**Comment by SoongNoonien** [comment]
Thanks, for the update but I've implemented this already (as I'm using gentoo). Sadly mpdevil isn't part of the default gentoo repo yet (https://bugs.gentoo.org/741150), these problems wouldn't occur if it were. I just haven't released a new version of mpdevil (and the .ebuild) yet because ubuntu is a bit outdated regarding python-mpd2 and I like to ship a .deb package.

**Comment by SoongNoonien** [comment]
> It's been over three years since you opened the bug and never had any feedback... maybe you would have more luck with [GURU](https://wiki.gentoo.org/wiki/Project:GURU#User_roles_and_responsibilities)?

Yes, this might be worth a shot.

**Comment by SoongNoonien** [comment]
> Another option is of course to create your own repository but I guess you provide the .ebuild in the releases section precisely because you don't want to maintain a repository just for one program?

Yes, exactly. This seemed way more convenient.
