### ISSUE TITLE
Right click actions?

### ISSUE THREAD

**Issue by s0ulslack** [SoongNoonien/mpdevil#83]
Would it be possible to right click an artist or album and add entirely?

**Comment by SoongNoonien** [comment]
Yes, this would certainly be possible. But I don't want those features (especially for artists) to be included in mpdevil. At some point in time it was implemented and I removed it because it didn't behave in a consistent way and I didn't want to come up with a more consistent implementation.

**Comment by rien333** [comment]
> At some point in time it was implemented and I removed it because it didn't behave in a consistent way and I didn't want to come up with a more consistent implementation.
 
 I would say that it also feels "inconsistent" to not be able to add albums from the album view to the queue using a right click/middle click. 
 
 Are you fundamentally against including enqueuing albums by right clicking them, or are you open for PRs? I feel implementing this behavior for artist is a little much, as you seem to agree.

**Comment by SoongNoonien** [comment]
> Are you fundamentally against including enqueuing albums by right clicking them, or are you open for PRs?

I'm sorry but implementing the feature is actually not the hard part here. The problem is to decide upon a desired behavior.

> I feel implementing this behavior for within the artist view is indeed a little much, as you seem to agree.

I simply decided to implement the right click menus for songs only. But this is what's hard about this, it is not entirely clear where to implement a menu and where not. For the time being I'll stand by my decision but this might change in the future.
